### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by drewstone** [PaulRBerg/foundry-template#18]
## Overview
Having trouble using this template out of the box and running my own tests. I reproduced that even with the base repo I can't get the tests to run, just contracts compile. What am I missing possibly?

## Running
- `forge init contracts-forge --template https://github.com/PaulRBerg/foundry-template`
- `forge install`
- `forge test`

### Result
```
**forge test**
compiling...
Compiling 1 files with 0.8.19
Compilation finished successfully
success.
```

**Comment by PaulRBerg** [comment]
Everything works fine on my end:

https://app.warp.dev/block/102pUfTeM3W86o6BloZKZj

Do you have Foundry up-to-date? Run `foundryup`, and consider upgrading `foundryup` itself, too (see Foundry's [README](https://github.com/foundry-rs/foundry#installation)).
