### ISSUE TITLE
Add forge coverage commands to scripts

### ISSUE THREAD

**Issue by mshakeg** [PaulRBerg/foundry-template#30]
`forge coverage` is an essential script. In addition, forge coverage compilation runs without an optimization so it's possible that `Stack Too Deep` errors may occur for `forge coverage` but not for `forge test`(if optimization is enabled). Hence having this script early in the development lifecycle can ensure that any `Stack Too Deep` issues are quickly resolved and not compounded with other `Stack Too Deep` errors over time, especially since foundry does not output the specific files that have this issue so it's not easy to isolate the `Stack Too Deep` errors(which is unlike hardhat in my experience at least, but if this is the case in hardhat too then add scripts there).

Suggested scripts to add:
```
    "test:coverage": "forge coverage",
    "test:coverage:report": "forge coverage --report lcov",
    "test:coverage:html": "forge coverage --report lcov && genhtml lcov.info --branch-coverage --output-dir coverage",
```

It might also be helpful to do `forge coverage` instead of `forge test` in CI.

**Comment by PaulRBerg** [comment]
Great idea.

I can't implement this right away but I would be happy to review a PR.

let's just skip the second script and rename the last to `coverage:report`.
