### ISSUE TITLE
PRBTest.sol breaks Vm.Log ?

### ISSUE THREAD

**Issue by nnnnicholas** [PaulRBerg/foundry-template#43]
Hi Paul,

I'm getting this odd error when trying to use `vm.getRecordedLogs()` in a test in a project using `foundry-template`.

`Type struct VmSafe.Log[] memory is not implicitly convertible to expected type struct VmSafe.Log[] memory.`

<img width="480" alt="image" src="https://github.com/PaulRBerg/foundry-template/assets/1418561/71dd414c-f59b-461e-b708-005913b3f8dc">

It's the first time I use this cheatcode, but someone in the Foundry support tg suggests that PRBTest might be causing the problem. Have you ever encountered this odd error?

Here is the tg mention of PRBTest possibly causing the problem: https://t.me/foundry_support/43751

<img width="344" alt="image" src="https://github.com/PaulRBerg/foundry-template/assets/1418561/e9628e71-3070-4c16-a1d4-d1119da2f9c7">

And here are my imports, in case relevant

<img width="931" alt="image" src="https://github.com/PaulRBerg/foundry-template/assets/1418561/06004e2b-7224-4e1a-ac9e-0077b234a824">

Thanks for any suggestions.

**Comment by PaulRBerg** [comment]
Sorry for this. The problem is PRBTest:

https://github.com/PaulRBerg/prb-test/issues/38
