### ISSUE TITLE
Fix prettier glob pattern in package.json

### ISSUE THREAD

**Issue by mariogutval** [paulrberg/foundry-template#48]
After some testing, the glob patterns in `package.json` are not hitting all the files when there are nested folders.

I suggest to add single quotes to prevent undesired behaviours (I tested it and everything was fixed with this approach):

![image](https://github.com/PaulRBerg/foundry-template/assets/29304078/e3c3ce41-3b57-40c0-9732-fe0f32316f3c)

**Comment by mariogutval** [comment]
Not only that file is ignored. You can compare the files that are hit prior to the fix and after:
![image](https://github.com/PaulRBerg/foundry-template/assets/29304078/00d701f8-56d2-4747-994b-cb29bfdb75a3)
![image](https://github.com/PaulRBerg/foundry-template/assets/29304078/d51ccc86-ab36-4ab2-8034-d045df49fc8c)

**Comment by PaulRBerg** [comment]
What OS and shell are you using?

We've been [using](https://github.com/sablier-labs/v2-core/blob/0a75661bc77f087620567265e1c7f973b1c504a8/package.json#L71-L72) `\"` at Sablier for a long time, and we've never had any issues with nested files.

**Comment by mariogutval** [comment]
> What OS and shell are you using?

macOS 14.4

> We've been [using](https://github.com/sablier-labs/v2-core/blob/0a75661bc77f087620567265e1c7f973b1c504a8/package.json#L71-L72) `\"` at Sablier for a long time, and we've never had any issues with nested files.

That also works for me!

**Comment by PaulRBerg** [comment]
I had thought that this repo was also using `\"`. Good catch, @mariogutval!
