### ISSUE TITLE
Bun run lint failing on prettier-plugin-solidity 

### ISSUE THREAD

**Issue by highskore** [PaulRBerg/foundry-template#55]
After switching to the bun version of the template (I've been using the pnpm version previously)
I'm always getting an error on 'prettier-plugin-solidity'

```
bun run lint
$ bun run lint:sol && bun run prettier:check
$ forge fmt --check && bun solhint {script,src,test}/**/*.sol
$ prettier --check "**/*.{json,md,yml}" --ignore-path ".prettierignore"
Checking formatting...
[error] Cannot find package 'prettier-plugin-solidity' imported from /Users/x/y/repo/noop.js
error: script "prettier:check" exited with code 1
error: script "lint" exited with code 1
```

**Comment by highskore** [comment]
Resolved by this btw `bun install prettier-plugin-solidity`

**Comment by PaulRBerg** [comment]
Hey! You might have installed other dependencies that require `prettier-plugin-solidity`.

Running `bun run lint` in a fresh clone of this template doesn't produce that warning.
