### ISSUE TITLE
`create` workflow does not run as expected

### ISSUE THREAD

**Issue by arr00** [PaulRBerg/foundry-template#58]
I'm not sure how the create workflow is intended to run, but in [a test repo](https://github.com/arr00/test) I created it is a bit odd. The `create` workflow does not run on the initial creation of the new repo, it only runs when you create a new branch or tag. I would expect it to run automatically on main with the initial commit.

Forked the template and switched to the `push` trigger and all worked as expected. https://github.com/arr00/test-new-template.

**Comment by PaulRBerg** [comment]
Good catch. The `create` workflow no longer works as expected.

It should be run when creating a new template via GitHub's `Use this Template` button.

The workflow was added by @ahmedali8. Maybe he can lend us a hand here? :D

**Comment by arr00** [comment]
[`push`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push) is the only trigger that mentions creating a repo from a template--I believe the conditional push trigger is the way to go.

**Comment by arr00** [comment]
Issue is relevant for https://github.com/PaulRBerg/hardhat-template as well.

**Comment by PaulRBerg** [comment]
Thanks
