### ISSUE TITLE
.vscode/settings.json don't follow foundry docs recommendations

### ISSUE THREAD

**Issue by 3esmit** [PaulRBerg/foundry-template#60]
See https://book.getfoundry.sh/config/vscode

Maybe this is a bad recommendation on the docs. If thats the case we can add an issue at their docs.

I noticed that Nomic extension might work better than the default most popular alternative (JuanBlanco) because Nomic uses solc version from project files. I requested JuanBlanco to support solc from project files https://github.com/juanfranblanco/vscode-solidity/issues/463

**Comment by PaulRBerg** [comment]
Not sure what the issue is?

Did you mean to say `.vscode/settings.json` instead of `.vscode/attributes.json`?

I wrote part of those recommendations in the Foundry docs: https://github.com/foundry-rs/book/pull/750

**Comment by 3esmit** [comment]
I mean that docs recommends JuanBlanco for matter, and here it's using Nomic

**Comment by PaulRBerg** [comment]
In this case, I'd recommend opening an issue/ PR in the Foundry Book repo to recommend using the Nomic extension instead.

Nomic is easier to configure and that's why I went with it (besides other benefits such as import hyperlinking).
